export interface ArticuloBodegaInterface {
  id?: number;
  codigoArticulo?: string;
  inventarioInicialCantidad?: number;
  inventarioInicialDinero?: number;
  inventarioInicialCostoUnitario?: number;
  inventarioFinalCantidad?: number;
  inventarioFinalDinero?: number;
  inventarioFinalCostoUnitario?: number;
  comprasCantidad?: number;
  comprasDinero?: number;
  devolucionComprasCantidad?: number;
  devolucionComprasDinero?: number;
  descuentoComprasCantidad?: number;
  descuentoComprasDinero?: number;
  ventasCantidad?: number;
  ventasDinero?: number;
  devolucionVentasCantidad?: number;
  devolucionVentasDinero?: number;
  descuentoVentasCantidad?: number;
  descuentoVentasDinero?: number;
  ingresosCantidad?: number;
  ingresosDinero?: number;
  ingresosTransferenciaCantidad?: number;
  ingresosTransferenciaDinero?: number;
  egresosCantidad?: number;
  egresosDinero?: number;
  egresosTransferenciaCantidad?: number;
  egresosTransferenciaDinero?: number;
  empresaProductora?: string;
  inventarioInicialCorteAnio?: number | string;
  inventarioInicialCorteMes?: number | string;
  periodoFechaInicio?: Date | string;
  periodoFechaFin?: Date | string;
  costoVentas?: number;
  costoGeneralVentas?: number;
  disponibleIncentivo?: number | boolean;
  habilitado?: number | boolean;
  cantidadPedida?: number;
  minimo?: number;
  maximo?: number;
  minimoAlerta?: number;
  ultimaCompraFecha?: Date | string;
  ultimaCompraCantidad?: number;
  ultimaCompraCosto?: number;
  ultimaCompraCostoDescuento?: number;
  ultimaVentaFecha?: Date | string;
  ultimaVentaCantidad?: number;
  ultimaVentaPrecio?: number;
  ultimaTransferenciaCosto?: number;
  idEdificio?: number;
  idEmpresa?: number;
  idPeriodo?: number;
  bodega?: number;
}
